---
global:
  time:
    time_start: "20211001_0001"
    time_end: "20211001_0002"
    t_parser: "%Y%m%d_%H%M"
    timedelta: 1

  subset:
    max_lat: 38.8
    min_lat: 33.0
    max_lon: 131.0
    min_lon: 124.5

  remove_nan: False

input:
  AWS:
    TYPE: AWS
    DATA_FOLDER: "/hdd_ext/ALPHA_data/AWS/"
    PRODUCTS:
      CSV:
        FILE_FORMAT: "%Y%m"
        BAND:
          1:
            item_path: "기온(°C)"
            pixel_number: 580
            line_number: 650
          2:
            item_path: "1분 강수량(mm)"
            pixel_number: 580
            line_number: 650
          3:
            item_path: "강수유무(유무)"
            pixel_number: 580
            line_number: 650
          4:
            item_path: "풍향(deg)"
            pixel_number: 580
            line_number: 650
          5:
            item_path: "풍속(m/s)"
            pixel_number: 580
            line_number: 650
          6:
            item_path: "현지기압(hPa)"
            pixel_number: 580
            line_number: 650
          7:
            item_path: "해면기압(hPa)"
            pixel_number: 580
            line_number: 650
          8:
            item_path: "습도(%)"
            pixel_number: 580
            line_number: 650
          9:
            item_path: "일사(MJ/m^2)"
            pixel_number: 580
            line_number: 650
          10:
            item_path: "일조(Sec)"
            pixel_number: 580
            line_number: 650

output:
  interpolate_method: 'nearest'
  pixel_number: 1000
  line_number: 1000
  sequence_length: 2
  cache: "/hdd_ext/ALPHA/save/datareader_AWS"
  use_cache: false
  save_cache: true
  cache_queue: 1000
  batch_size: 1
  window:
    width: 500
    height: 500
    stride: 500
